#Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
#Fabric Properties
loader_version=0.19.3
loom_version=1.16-SNAPSHOT
# Mod Properties
mod_id=bird-addon
mod_name=BirdAddon
mod_description=Bird's m4 addons
mod_version=0.0.9
maven_group=com.barefootbird
archives_base_name=bird-addon
# Mod Dependencies
fabric_kotlin_version=1.13.12+kotlin.2.4.0
devauth_version=1.2.2
commodore_version=1.0.1
# Other Properties
kotlin_version=2.4.0
kotlin.code.style=official
minecraft_lwjgl_version=3.4.1

# Version Specific Things

# 26.1.2
fabric_api_version=0.151.0+26.1.2
minecraft_version=26.1.2
odin_version=0.2.3
